### ISSUE TITLE
Installing trollstore using this method will result in failure to update apps in app store

### ISSUE THREAD

**Issue by A-Cepheus** [alfiecg24/TrollInstallerX#18]
Specifically, after capturing the log, it is found that the installation report error permissions are denied

**Comment by alfiecg24** [comment]
Which app is this? Which iOS version? Which device?

**Comment by A-Cepheus** [comment]
> Which app is this? Which iOS version? Which device?

iPhone 14 Pro with iOS 16.6.1, most apps cannot be updated (clicking the update button turns back to the update button after rotating), and even after resetting the phone once, the problem can still be reproduced.

**Comment by alfiecg24** [comment]
I see - where is this permission denied error?

**Comment by A-Cepheus** [comment]
> I see - where is this permission denied error?

The error log looks like
`Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo=`
A more detailed log requires me to extract it again later.

**Comment by alfiecg24** [comment]
Do you have Filza installed?

**Comment by A-Cepheus** [comment]
> Do you have Filza installed?

yes

**Comment by alfiecg24** [comment]
Please check the permissions of /var/containers, /var/containers/Bundle and /var/containers/Bundle/Application.

**Comment by Ptr-gjkl** [comment]
Hello
I have encountered the same issue and with filza installed permissions across three paths is:
owner:read,write,execute
Group:read,execute 
Others:read,execute

**Comment by alfiecg24** [comment]
I need to know which user/group has owner ship of the directories.

**Comment by Ptr-gjkl** [comment]
for var/containers and /bundle
Owner:root
Group:wheel
for var/containers/bundle/application
owner:mobile
group:mobile

**Comment by A-Cepheus** [comment]
![fa7f65247709341646b37695d885e84](https://github.com/user-attachments/assets/4b87dfaa-32c7-4937-ad12-b7f17f79ad8b)
![26cac878e235be828bdb3c54f45b02c](https://github.com/user-attachments/assets/94af5193-134e-4855-9441-6acd3d5656bf)
![59e3b6140af7eabd7dfa682fab75610](https://github.com/user-attachments/assets/1ee8b42c-fb5b-4b7d-bc7a-38eac5e8ca66)

**Comment by A-Cepheus** [comment]
> ![fa7f65247709341646b37695d885e84](https://private-user-images.githubusercontent.com/60658915/354309664-4b87dfaa-32c7-4937-ad12-b7f17f79ad8b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzExMTYsIm5iZiI6MTcyMjUzMDgxNiwicGF0aCI6Ii82MDY1ODkxNS8zNTQzMDk2NjQtNGI4N2RmYWEtMzJjNy00OTM3LWFkMTItYjdmMTdmNzlhZDhiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE2NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYmE4NmIwYWI0MzE3ZWNhNmUxYzdlM2QzMGFiOGFlNGEwZTM3MzRmM2MzYmUyNzk3MTk3OTdjOThmNzM1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QWQVNl-7gRV2bMF6tcxr-sgI5OpHA2bdddAMffkPCYs) ![26cac878e235be828bdb3c54f45b02c](https://private-user-images.githubusercontent.com/60658915/354309697-94af5193-134e-4855-9441-6acd3d5656bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzExMTYsIm5iZiI6MTcyMjUzMDgxNiwicGF0aCI6Ii82MDY1ODkxNS8zNTQzMDk2OTctOTRhZjUxOTMtMTM0ZS00ODU1LTk0NDEtNmFjZDNkNTY1NmJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE2NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMmVmZWIyMjExOTZmNGYxNzM4OGZjMTUyZDViZGVhMDBjNmQyYzRmNzc3OWYzZGZiMjZhZWYzMzcxODI4MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RW9H94fKmhhjsy6u4L34aUM-Akqzh7mp85SzhBs7UP8) ![59e3b6140af7eabd7dfa682fab75610](https://private-user-images.githubusercontent.com/60658915/354309719-1ee8b42c-fb5b-4b7d-bc7a-38eac5e8ca66.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzExMTYsIm5iZiI6MTcyMjUzMDgxNiwicGF0aCI6Ii82MDY1ODkxNS8zNTQzMDk3MTktMWVlOGI0MmMtZmI1Yi00YjdkLWJjN2EtMzhlYWM1ZThjYTY2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE2NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDUxNDNlOGM0ZjYwNWMyYTAzNTMxMGI5YTY4ZTMwOTg4YTBlN2Y2YmRmN2M4MDNmOTAzYjBmZDI1YjBmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tPxNLq1h-J497-3z2AAL18Zyv1TfzIvc1uWo4b2JpU4)

sorry for the chinese, my permissions same as the permissions of the person above

**Comment by alfiecg24** [comment]
Is the issue resolved?

**Comment by Ptr-gjkl** [comment]
Sorry for late update
i had to reset my device(unrelated to trollstore)installed trollstore via trollinstaller x again but didn’t install “troll apps” and the issue was resolved so at least for me this issue seemed to be caused by installing “troll apps” and not “trollinstaller” x
Tested Devices:
iPhone 13 Pro Max iOS 16.6.1
iPhone X                 iOS 16.6.1
Thank you alfiecg for creating trollinstaller x and help and dedication for resolving issues

**Comment by alfiecg24** [comment]
That sounds similar to an issue I had investigated I few weeks ago. Thank you for your response, I'm glad the issue is now resolved.

**Comment by A-Cepheus** [comment]
I would like to know if there is a way to solve this problem without resetting the phone, as setting _installd does not solve the issue. Group cannot be set to _installd. It prompts, "You do not have permission to store the file 'containers' in the folder 'var'"

**Comment by thatsprettygood** [comment]
@alfiecg24 How is this issue solved?

**Comment by A-Cepheus** [comment]
> @alfiecg24 How is this issue solved?

The folder permissions for some apps are incorrect. You only need to manually or use a script to batch modify the permissions to the correct ones to solve the problem.
You can download a new app to observe what the correct permissions are.
app folders are in /var/containers/bundle/application

**Comment by thatsprettygood** [comment]
> > @alfiecg24 How is this issue solved?
> 
> The folder permissions for some apps are incorrect. You only need to manually or use a script to batch modify the permissions to the correct ones to solve the problem. You can download a new app to observe what the correct permissions are. app folders are in /var/containers/bundle/application

Is there anywhere I can learn to do this? This just seems like an issue that should be fixed instead of the user having to fix it themselves.

**Comment by alfiecg24** [comment]
I have never experienced nor been able to reproduce this issue. I have also seen people who have had this issue without using TrollInstallerX. It seems it could also be an issue with some app that people are installing with TrollStore.

**Comment by thatsprettygood** [comment]
> I have never experienced nor been able to reproduce this issue. I have also seen people who have had this issue without using TrollInstallerX. It seems it could also be an issue with some app that people are installing with TrollStore.

I hadn't installed any apps before the error occurred.
I fixed it by uninstalling trollstore and restarting my device.
It seems that this problem only occurs on 16.6.1.
